# Generated by Django 6.0 on 2025-12-17 08:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='foodics_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Foodics Branch ID'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.restaurantcompany', verbose_name='الشركة التابعة'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(max_length=255, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branch', to=settings.AUTH_USER_MODEL, verbose_name='مدير الفرع'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الفرع'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='waste_threshold',
            field=models.FloatField(default=5.0, help_text='النسبة المئوية المسموح بها للهدر قبل التنبيه', verbose_name='حد الهدر (%)'),
        ),
        migrations.AlterField(
            model_name='restaurantcompany',
            name='foodics_token',
            field=models.TextField(blank=True, null=True, verbose_name='Foodics Access Token'),
        ),
        migrations.AlterField(
            model_name='restaurantcompany',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_company', to=settings.AUTH_USER_MODEL, verbose_name='المدير العام'),
        ),
        migrations.AlterField(
            model_name='restaurantcompany',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الشركة/المطعم'),
        ),
        migrations.AlterField(
            model_name='restaurantcompany',
            name='subscription_status',
            field=models.BooleanField(default=True, verbose_name='حالة الاشتراك'),
        ),
    ]
