# apps/analytics/models.py
from django.db import models
from apps.core.models import Branch

class WasteReport(models.Model):
    branch = models.ForeignKey(
        Branch, 
        on_delete=models.CASCADE, 
        related_name='waste_reports'
    )
    # استخدمنا Decimal للدقة المالية
    total_waste_value = models.DecimalField(max_digits=10, decimal_places=2) 
    
    ai_analysis = models.TextField(help_text="Generated by AI Engine")
    generated_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Report #{self.id} - {self.branch.name}"