# apps/analytics/models.py
from django.db import models
from apps.core.models import Branch

class WasteReport(models.Model):
    branch = models.ForeignKey(
        Branch, 
        on_delete=models.CASCADE, 
        related_name='waste_reports'
    )
    # استخدمنا Decimal للدقة المالية
    total_waste_value = models.DecimalField(max_digits=10, decimal_places=2) 
    
    ai_analysis = models.TextField(help_text="Generated by AI Engine")
    generated_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Report #{self.id} - {self.branch.name}"

class WasteLog(models.Model):
    WASTE_REASONS = [
        ('expired', 'منتهي الصلاحية'),
        ('damaged', 'تالف / مكسور'),
        ('prepared_incorrectly', 'إعداد خاطئ'),
        ('spilled', 'انسكاب'),
        ('other', 'أخرى'),
    ]

    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, verbose_name="الفرع")
    # نستخدم String reference لتجنب Circular Import إذا أمكن، أو نستورد داخل الدالة، لكن هنا نحتاجه في التعريف
    # سنضيف Imports في الأعلى
    product = models.ForeignKey('inventory.Product', on_delete=models.CASCADE, verbose_name="المنتج")
    
    quantity = models.FloatField(verbose_name="الكمية المهدرة")
    reason = models.CharField(max_length=50, choices=WASTE_REASONS, verbose_name="سبب الهدر")
    notes = models.TextField(blank=True, null=True, verbose_name="ملاحظات إضافية")
    
    submitted_by = models.ForeignKey('authentication.User', on_delete=models.SET_NULL, null=True, verbose_name="الموظف المسؤول")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="تاريخ التسجيل")

    def __str__(self):
        return f"{self.product.name} - {self.quantity}"