# Generated by Django 6.0 on 2025-12-16 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodicsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('batch_id', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('stock_level', models.IntegerField()),
                ('sales_velocity', models.FloatField(default=0.0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.branch')),
            ],
            options={
                'unique_together': {('branch', 'sku', 'batch_id')},
            },
        ),
    ]
