# Generated by Django 6.0 on 2025-12-17 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0002_product_stockitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'verbose_name': 'عنصر مخزون', 'verbose_name_plural': 'عناصر المخزون'},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='التصنيف'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='kg', max_length=20, verbose_name='وحدة القياس'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='batch_id',
            field=models.CharField(default='BATCH-000', max_length=100, verbose_name='رقم التشغيلة/الباتش'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockitem',
            name='initial_quantity',
            field=models.FloatField(default=0, verbose_name='الكمية الأصلية'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='last_synced',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='sales_velocity',
            field=models.FloatField(default=1.0, verbose_name='معدل الاستهلاك اليومي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='رمز SKU'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='expiry_date',
            field=models.DateField(default='2025-01-01', verbose_name='تاريخ الانتهاء'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='الكمية الحالية'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('branch', 'product', 'batch_id')},
        ),
        migrations.DeleteModel(
            name='FoodicsData',
        ),
    ]
