# Generated by Django 6.0 on 2025-12-20 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_branch_created_at_branch_foodics_id_and_more'),
        ('inventory', '0003_alter_stockitem_options_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.restaurantcompany', verbose_name='الشركة المالكة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('meat', 'لحوم'), ('chicken', 'دجاج'), ('vegetables', 'خضروات'), ('fruits', 'فواكه'), ('dairy', 'ألبان وأجبان'), ('drinks', 'مشروبات'), ('bakery', 'مخبوزات'), ('spices', 'بهارات'), ('packaging', 'تغليف'), ('other', 'أخرى')], max_length=50, null=True, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'كجم'), ('g', 'جم'), ('liter', 'لتر'), ('ml', 'مل'), ('pcs', 'حبة'), ('box', 'كرتون')], default='kg', max_length=20, verbose_name='وحدة القياس'),
        ),
    ]
