# Generated by Django 6.0 on 2025-12-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_quantity',
            field=models.FloatField(default=5.0, verbose_name='حد النقص (Alert Threshold)'),
        ),
    ]
