# Generated by Django 6.0 on 2025-12-20 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_branch_created_at_branch_foodics_id_and_more'),
        ('inventory', '0006_product_minimum_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStockSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_quantity', models.FloatField(default=5.0, verbose_name='حد النقص الخاص بالفرع')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_settings', to='core.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_settings', to='inventory.product')),
            ],
            options={
                'verbose_name': 'إعداد مخزون الفرع',
                'verbose_name_plural': 'إعدادات مخزون الفروع',
                'unique_together': {('branch', 'product')},
            },
        ),
    ]
