# Generated by Django 6.0 on 2025-12-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalrequest',
            name='manager_response',
            field=models.TextField(blank=True, null=True, verbose_name='رد الإدارة'),
        ),
    ]
