# Generated by Django 5.2.8 on 2025-12-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_operationalrequest_manager_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
