# Generated by Django 6.0 on 2025-12-16 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_waste_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ai_analysis', models.TextField(help_text='Generated by AI Engine')),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_reports', to='core.branch')),
            ],
        ),
    ]
