# Generated by Django 6.0 on 2025-12-20 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0002_branch_created_at_branch_foodics_id_and_more'),
        ('inventory', '0004_product_company_alter_product_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='الكمية المهدرة')),
                ('reason', models.CharField(choices=[('expired', 'منتهي الصلاحية'), ('damaged', 'تالف / مكسور'), ('prepared_incorrectly', 'إعداد خاطئ'), ('spilled', 'انسكاب'), ('other', 'أخرى')], max_length=50, verbose_name='سبب الهدر')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='الفرع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='المنتج')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول')),
            ],
        ),
    ]
