# Generated by Django 6.0 on 2025-12-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'مدير مطعم (مشرف عام)'), ('branch_manager', 'مدير فرع')], default='branch_manager', max_length=20, verbose_name='نوع الحساب'),
        ),
    ]
