# Generated by Django 6.0 on 2025-12-19 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
        ('core', '0002_branch_created_at_branch_foodics_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_managers', to='core.branch', verbose_name='الفرع المكلف به'),
        ),
    ]
