# Generated by Django 5.2.8 on 2025-12-21 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='المستلم')),
                ('email_type', models.CharField(choices=[('welcome', 'إيميل ترحيب'), ('activation', 'تفعيل الحساب'), ('password_reset', 'إعادة تعيين كلمة المرور'), ('system_update', 'تحديث النظام'), ('other', 'أخرى')], max_length=50, verbose_name='نوع الإيميل')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('body', models.TextField(verbose_name='المحتوى')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال؟')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
            ],
            options={
                'verbose_name': 'سجل إيميل',
                'verbose_name_plural': 'سجلات الإيميلات',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإشعار')),
                ('message', models.TextField(verbose_name='نص الإشعار')),
                ('scheduled_time', models.DateTimeField(verbose_name='موعد التحديث')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال؟')),
                ('send_email', models.BooleanField(default=True, verbose_name='إرسال إيميل؟')),
                ('send_notification', models.BooleanField(default=True, verbose_name='إرسال إشعار داخلي؟')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'تحديث النظام',
                'verbose_name_plural': 'تحديثات النظام',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('notification_type', models.CharField(choices=[('system_update', 'تحديث النظام'), ('welcome', 'ترحيب'), ('alert', 'تنبيه'), ('info', 'معلومة')], default='info', max_length=50, verbose_name='نوع الإشعار')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('related_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.systemupdate', verbose_name='التحديث المرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
