# Generated by Django 5.2.8 on 2025-12-21 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemupdate',
            name='target_type',
            field=models.CharField(choices=[('all', 'جميع المستخدمين'), ('managers', 'المدراء فقط'), ('selected', 'مستخدمين محددين')], default='managers', max_length=20, verbose_name='نوع الاستهداف'),
        ),
        migrations.AddField(
            model_name='systemupdate',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='targeted_updates', to=settings.AUTH_USER_MODEL, verbose_name='المستخدمين المستهدفين'),
        ),
    ]
